package com.shangame.hxjsq.storage.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shangame.hxjsq.storage.model.ResultEntity;
import com.shangame.hxjsq.storage.model.ScoreRecordEntity;

import com.shangame.hxjsq.storage.db.ResultEntityDao;
import com.shangame.hxjsq.storage.db.ScoreRecordEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig resultEntityDaoConfig;
    private final DaoConfig scoreRecordEntityDaoConfig;

    private final ResultEntityDao resultEntityDao;
    private final ScoreRecordEntityDao scoreRecordEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        resultEntityDaoConfig = daoConfigMap.get(ResultEntityDao.class).clone();
        resultEntityDaoConfig.initIdentityScope(type);

        scoreRecordEntityDaoConfig = daoConfigMap.get(ScoreRecordEntityDao.class).clone();
        scoreRecordEntityDaoConfig.initIdentityScope(type);

        resultEntityDao = new ResultEntityDao(resultEntityDaoConfig, this);
        scoreRecordEntityDao = new ScoreRecordEntityDao(scoreRecordEntityDaoConfig, this);

        registerDao(ResultEntity.class, resultEntityDao);
        registerDao(ScoreRecordEntity.class, scoreRecordEntityDao);
    }
    
    public void clear() {
        resultEntityDaoConfig.clearIdentityScope();
        scoreRecordEntityDaoConfig.clearIdentityScope();
    }

    public ResultEntityDao getResultEntityDao() {
        return resultEntityDao;
    }

    public ScoreRecordEntityDao getScoreRecordEntityDao() {
        return scoreRecordEntityDao;
    }

}
