package com.shangame.hxjsq.storage.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.shangame.hxjsq.storage.model.ResultEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RESULT_ENTITY".
*/
public class ResultEntityDao extends AbstractDao<ResultEntity, Long> {

    public static final String TABLENAME = "RESULT_ENTITY";

    /**
     * Properties of entity ResultEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Name2 = new Property(2, String.class, "name2", false, "NAME2");
        public final static Property Name3 = new Property(3, String.class, "name3", false, "NAME3");
        public final static Property Duplicate = new Property(4, int.class, "duplicate", false, "DUPLICATE");
        public final static Property Duplicate2 = new Property(5, int.class, "duplicate2", false, "DUPLICATE2");
        public final static Property Duplicate3 = new Property(6, int.class, "duplicate3", false, "DUPLICATE3");
        public final static Property Accumulative = new Property(7, double.class, "accumulative", false, "ACCUMULATIVE");
        public final static Property Accumulative2 = new Property(8, double.class, "accumulative2", false, "ACCUMULATIVE2");
        public final static Property Accumulative3 = new Property(9, double.class, "accumulative3", false, "ACCUMULATIVE3");
        public final static Property Score = new Property(10, double.class, "score", false, "SCORE");
        public final static Property Score2 = new Property(11, double.class, "score2", false, "SCORE2");
        public final static Property Score3 = new Property(12, double.class, "score3", false, "SCORE3");
        public final static Property Datetime = new Property(13, long.class, "datetime", false, "DATETIME");
        public final static Property Date = new Property(14, String.class, "date", false, "DATE");
        public final static Property Number = new Property(15, long.class, "number", false, "NUMBER");
    }


    public ResultEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ResultEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RESULT_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"NAME2\" TEXT," + // 2: name2
                "\"NAME3\" TEXT," + // 3: name3
                "\"DUPLICATE\" INTEGER NOT NULL ," + // 4: duplicate
                "\"DUPLICATE2\" INTEGER NOT NULL ," + // 5: duplicate2
                "\"DUPLICATE3\" INTEGER NOT NULL ," + // 6: duplicate3
                "\"ACCUMULATIVE\" REAL NOT NULL ," + // 7: accumulative
                "\"ACCUMULATIVE2\" REAL NOT NULL ," + // 8: accumulative2
                "\"ACCUMULATIVE3\" REAL NOT NULL ," + // 9: accumulative3
                "\"SCORE\" REAL NOT NULL ," + // 10: score
                "\"SCORE2\" REAL NOT NULL ," + // 11: score2
                "\"SCORE3\" REAL NOT NULL ," + // 12: score3
                "\"DATETIME\" INTEGER NOT NULL ," + // 13: datetime
                "\"DATE\" TEXT," + // 14: date
                "\"NUMBER\" INTEGER NOT NULL );"); // 15: number
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RESULT_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ResultEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String name2 = entity.getName2();
        if (name2 != null) {
            stmt.bindString(3, name2);
        }
 
        String name3 = entity.getName3();
        if (name3 != null) {
            stmt.bindString(4, name3);
        }
        stmt.bindLong(5, entity.getDuplicate());
        stmt.bindLong(6, entity.getDuplicate2());
        stmt.bindLong(7, entity.getDuplicate3());
        stmt.bindDouble(8, entity.getAccumulative());
        stmt.bindDouble(9, entity.getAccumulative2());
        stmt.bindDouble(10, entity.getAccumulative3());
        stmt.bindDouble(11, entity.getScore());
        stmt.bindDouble(12, entity.getScore2());
        stmt.bindDouble(13, entity.getScore3());
        stmt.bindLong(14, entity.getDatetime());
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(15, date);
        }
        stmt.bindLong(16, entity.getNumber());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ResultEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String name2 = entity.getName2();
        if (name2 != null) {
            stmt.bindString(3, name2);
        }
 
        String name3 = entity.getName3();
        if (name3 != null) {
            stmt.bindString(4, name3);
        }
        stmt.bindLong(5, entity.getDuplicate());
        stmt.bindLong(6, entity.getDuplicate2());
        stmt.bindLong(7, entity.getDuplicate3());
        stmt.bindDouble(8, entity.getAccumulative());
        stmt.bindDouble(9, entity.getAccumulative2());
        stmt.bindDouble(10, entity.getAccumulative3());
        stmt.bindDouble(11, entity.getScore());
        stmt.bindDouble(12, entity.getScore2());
        stmt.bindDouble(13, entity.getScore3());
        stmt.bindLong(14, entity.getDatetime());
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(15, date);
        }
        stmt.bindLong(16, entity.getNumber());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ResultEntity readEntity(Cursor cursor, int offset) {
        ResultEntity entity = new ResultEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name2
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name3
            cursor.getInt(offset + 4), // duplicate
            cursor.getInt(offset + 5), // duplicate2
            cursor.getInt(offset + 6), // duplicate3
            cursor.getDouble(offset + 7), // accumulative
            cursor.getDouble(offset + 8), // accumulative2
            cursor.getDouble(offset + 9), // accumulative3
            cursor.getDouble(offset + 10), // score
            cursor.getDouble(offset + 11), // score2
            cursor.getDouble(offset + 12), // score3
            cursor.getLong(offset + 13), // datetime
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // date
            cursor.getLong(offset + 15) // number
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ResultEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName2(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName3(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDuplicate(cursor.getInt(offset + 4));
        entity.setDuplicate2(cursor.getInt(offset + 5));
        entity.setDuplicate3(cursor.getInt(offset + 6));
        entity.setAccumulative(cursor.getDouble(offset + 7));
        entity.setAccumulative2(cursor.getDouble(offset + 8));
        entity.setAccumulative3(cursor.getDouble(offset + 9));
        entity.setScore(cursor.getDouble(offset + 10));
        entity.setScore2(cursor.getDouble(offset + 11));
        entity.setScore3(cursor.getDouble(offset + 12));
        entity.setDatetime(cursor.getLong(offset + 13));
        entity.setDate(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setNumber(cursor.getLong(offset + 15));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ResultEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ResultEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ResultEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
